import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const SIGN_TYPES = ['accounts', 'pm', 'manager', 'authorized', 'seal'];
export const PAGE_BREAK_THRESHOLDS = { PAGE_2: 12, PAGE_3: 48 };

export const DEFAULT_COLUMNS = [
  { id: 'description', label: 'Item Description', type: 'text' },
  { id: 'quantity', label: 'Qty', type: 'number' },
  { id: 'unitPrice', label: 'Unit Price(QR)', type: 'number' },
  { id: 'totalPrice', label: 'Total Price(QR)', type: 'calculated' },
];

export const DEFAULT_HIRE_ORDER_DATA = {
  vendor: '',
  date: '',
  hireOrderRef: '',
  quoteNo: '',
  attention: '',
  designation: '',
  requestText: '',
  items: [],
  columns: DEFAULT_COLUMNS,
  totalAmount: 0,
  termsAndConditions: [
    'Terms & Conditions',
    'Payment will be made within 90 days from the day of submission of invoice',
  ],
  signatures: {
    accountsDept: 'ACCOUNTS DEPT',
    purchasingManager: 'PURCHASING MANAGER',
    operationsManager: 'OPERATIONS MANAGER',
    authorizedSignatory: 'CEO/MD',
  },
};

export const DEFAULT_SIGNATURE_FLAGS = {
  pmSigned: false,
  accountsSigned: false,
  managerSigned: false,
  ceoSigned: false,
};

export const DEFAULT_SIGNATURE_STATES = {
  accounts: { url: '', loading: false },
  pm: { url: '', loading: false },
  manager: { url: '', loading: false },
  authorized: { url: '', loading: false },
  seal: { url: '', loading: false },
};

export const BG_STYLE_KEYS = ['background', 'backgroundImage', 'backgroundSize', 'backgroundRepeat', 'backgroundPosition', 'backgroundAttachment'];

export const formatCurrency = (value) =>
  (value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export const signatoryRole = (name) => name === 'CEO' ? '(CEO)' : '(MANAGING DIRECTOR)';

export const buildTimestamp = () => {
  const date = new Date();
  const d = date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const t = date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  return `This document was generated by the system on ${d}, at ${t}.`;
};

export const captureElementToCanvas = async (element) => {
  const rootOriginal = {};
  BG_STYLE_KEYS.forEach((key) => { rootOriginal[key] = element.style[key]; });
  Object.assign(element.style, {
    background: '#FFFFFF',
    backgroundImage: 'none',
    backgroundSize: 'auto',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'initial',
    backgroundAttachment: 'initial',
  });

  const children = element.querySelectorAll('*');
  const childOriginals = [];
  children.forEach((child, idx) => {
    childOriginals[idx] = {};
    BG_STYLE_KEYS.forEach((key) => { childOriginals[idx][key] = child.style[key]; });
    if (child.style.backgroundImage && /grid|linear-gradient|repeating/.test(child.style.backgroundImage)) {
      child.style.backgroundImage = 'none';
    }
  });

  const canvas = await html2canvas(element, {
    scale: 2,
    logging: false,
    useCORS: true,
    allowTaint: false,
    scrollX: 0,
    scrollY: 0,
    windowWidth: element.scrollWidth,
    windowHeight: element.scrollHeight,
    backgroundColor: '#FFFFFF',
    ignoreElements: (el) => {
      const cs = window.getComputedStyle(el);
      return cs.backgroundImage && /grid|repeating/.test(cs.backgroundImage);
    },
    removeContainer: true,
    foreignObjectRendering: false,
  });

  Object.assign(element.style, rootOriginal);
  children.forEach((child, idx) => Object.assign(child.style, childOriginals[idx]));

  return canvas;
};

export const buildPdf = async () => {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const allDocuments = document.querySelectorAll('.hire-order-document');

  for (let i = 0; i < allDocuments.length; i++) {
    const canvas = await captureElementToCanvas(allDocuments[i]);
    const imgData = canvas.toDataURL('image/png', 1.0);
    const imgWidth = 210;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    if (i > 0) pdf.addPage();
    pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
  }

  return pdf;
};
