import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { DEFAULT_COLUMNS } from '../constants/hire.order.report.constant';

const BG_STYLE_KEYS = ['background', 'backgroundImage', 'backgroundSize', 'backgroundRepeat', 'backgroundPosition', 'backgroundAttachment'];
const PAPER_WIDTH_MM = 297;
const PAPER_HEIGHT_MM = 420;

export const formatCurrency = (value) =>
  (value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export const signatoryRole = (name) => name === 'CEO' ? '(CEO)' : '(MANAGING DIRECTOR)';

export const buildTimestamp = () => {
  const date = new Date();
  const d = date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const t = date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  return `This document was generated by the system on ${d}, at ${t}.`;
};

const waitForImages = (element) => {
  const images = Array.from(element.querySelectorAll('img'));
  return Promise.all(images.map((img) => {
    if (img.complete && img.naturalHeight !== 0) return Promise.resolve();
    return new Promise((resolve) => {
      img.addEventListener('load', resolve, { once: true });
      img.addEventListener('error', resolve, { once: true });
    });
  }));
};

const nextFrame = () => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));

const KERNING_FIX_ID = 'html2canvas-kerning-fix-hire-order';

const injectKerningFix = () => {
  const style = document.createElement('style');
  style.id = KERNING_FIX_ID;
  style.textContent = `
    .a2-paper, .a2-paper * {
      font-kerning: none !important;
      font-variant-ligatures: none !important;
      -webkit-font-feature-settings: "liga" 0, "kern" 0 !important;
      font-feature-settings: "liga" 0, "kern" 0 !important;
      letter-spacing: normal !important;
      text-rendering: geometricPrecision !important;
    }
  `;
  document.head.appendChild(style);
  return style;
};

const removeKerningFix = (style) => {
  if (style && style.parentNode) style.parentNode.removeChild(style);
};

export const captureElementToCanvas = async (element) => {
  const rootOriginal = {};
  BG_STYLE_KEYS.forEach((key) => { rootOriginal[key] = element.style[key]; });
  Object.assign(element.style, {
    background: '#FFFFFF',
    backgroundImage: 'none',
    backgroundSize: 'auto',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'initial',
    backgroundAttachment: 'initial',
  });

  const children = element.querySelectorAll('*');
  const childOriginals = [];
  children.forEach((child, idx) => {
    childOriginals[idx] = {};
    BG_STYLE_KEYS.forEach((key) => { childOriginals[idx][key] = child.style[key]; });
    if (child.style.backgroundImage && /grid|linear-gradient|repeating/.test(child.style.backgroundImage)) {
      child.style.backgroundImage = 'none';
    }
  });

  const kerningStyle = injectKerningFix();

  await document.fonts.ready;
  await waitForImages(element);
  await nextFrame();

  let canvas;
  try {
    canvas = await html2canvas(element, {
      scale: 2,
      logging: false,
      useCORS: true,
      allowTaint: false,
      scrollX: 0,
      scrollY: 0,
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight,
      backgroundColor: '#FFFFFF',
      foreignObjectRendering: false,
      letterRendering: true,
      ignoreElements: (el) => {
        const cs = window.getComputedStyle(el);
        return cs.backgroundImage && /grid|repeating/.test(cs.backgroundImage);
      },
      removeContainer: true,
    });
  } finally {
    removeKerningFix(kerningStyle);
    Object.assign(element.style, rootOriginal);
    children.forEach((child, idx) => Object.assign(child.style, childOriginals[idx]));
  }

  return canvas;
};

export const buildPdf = async () => {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: [PAPER_WIDTH_MM, PAPER_HEIGHT_MM] });
  const allDocuments = document.querySelectorAll('.a2-paper');
  await document.fonts.ready;

  for (let i = 0; i < allDocuments.length; i++) {
    const canvas = await captureElementToCanvas(allDocuments[i]);
    const imgData = canvas.toDataURL('image/png', 1.0);
    const imgHeight = (canvas.height * PAPER_WIDTH_MM) / canvas.width;

    if (i > 0) pdf.addPage([PAPER_WIDTH_MM, PAPER_HEIGHT_MM], 'portrait');
    pdf.addImage(imgData, 'PNG', 0, 0, PAPER_WIDTH_MM, imgHeight);
  }

  return pdf;
};

export const buildOverrideMessage = (unsignedAboveRoles) =>
  `The following ${unsignedAboveRoles.length > 1 ? 'people have' : 'person has'} not yet signed this document:\n\n${unsignedAboveRoles.join(', ')}\n\nYou can wait for them to sign first, or override and sign now. If you override, they will be notified to sign.`;

export const extractFirstName = (str) => (str ? str.split('-')[0].trim() : '');

export const getFileName = (hireOrderData) => `HO-${hireOrderData.hireOrderRef}-${hireOrderData.vendor}`;

export const parseValidEmails = (emails) => emails.filter((e) => e?.includes('@'));

export const parseEmailInput = (value) => value.split(',').map((e) => e.trim()).filter(Boolean);

export const getEffectiveColumns = (data) => (data.columns?.length ? data.columns : DEFAULT_COLUMNS);

export const splitHeaderLabel = (label = '') => {
  if (!label) return [label];
  const slashIndex = label.indexOf('/');
  if (slashIndex !== -1 && slashIndex < label.length - 1) {
    return [label.slice(0, slashIndex + 1), label.slice(slashIndex + 1).trim()];
  }
  if (label.length > 18) {
    const mid = Math.floor(label.length / 2);
    let breakAt = label.lastIndexOf(' ', mid);
    if (breakAt === -1) breakAt = label.indexOf(' ', mid);
    if (breakAt !== -1) return [label.slice(0, breakAt).trim(), label.slice(breakAt).trim()];
  }
  return [label];
};