import { forwardRef, useEffect, useRef, useState } from 'react';

import Logo      from '@/assets/images/al-ansari-color.png';
import Address   from '@/assets/images/al-ansari-full-address.png';
import ContactUs from '@/assets/images/footer.png';

import './A2Paper.css';

const buildGeneratedTimestamp = () => {
  const date = new Date();
  const d = date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const t = date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  return `This document was generated by the system on ${d}, at ${t}.`;
};

const A2Paper = forwardRef(function A2Paper({ children, bodyRef, probe }, ref) {
  return (
    <div ref={ref} className={`a2-paper${probe ? ' a2-paper-probe' : ''}`} data-a2-paper-ready="true">
      <div className="a2-paper-header">
        <img className="a2-paper-logo" src={Logo} alt="Company Logo" crossOrigin="anonymous" />
        <img className="a2-paper-address" src={Address} alt="AL Ansari Transport & Enterprises W.L.L" crossOrigin="anonymous" />
      </div>

      <div className="a2-paper-body" ref={bodyRef}>
        {children}
      </div>

      <div className="a2-paper-footer">
        <div className="a2-paper-footer-timestamp">{buildGeneratedTimestamp()}</div>
        <img className="a2-paper-footer-contact" src={ContactUs} alt="" crossOrigin="anonymous" />
      </div>
    </div>
  );
});

export const PAGE_CONTENT_GAP_REM = 4;

export const useA2PageBudget = () => {
  const bodyProbeRef = useRef(null);
  const [budget, setBudget] = useState(null);

  useEffect(() => {
    const el = bodyProbeRef.current;
    if (!el) return undefined;

    const measure = () => {
      const gapPx = PAGE_CONTENT_GAP_REM * parseFloat(getComputedStyle(document.documentElement).fontSize);
      setBudget(Math.max(0, el.clientHeight - gapPx));
    };

    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return { bodyProbeRef, budget };
};

export const useA2BlockPagination = (blocks, budget, firstPageOffset = 0) => {
  const measureRef = useRef(null);
  const [pages, setPages] = useState(() => (blocks.length ? [blocks] : [[]]));

  useEffect(() => {
    if (!budget || !measureRef.current || !blocks.length) {
      setPages(blocks.length ? [blocks] : [[]]);
      return;
    }

    const nodes = Array.from(measureRef.current.children);
    const result = [];
    let current = [];
    let currentHeight = 0;

    blocks.forEach((block, index) => {
      const height = nodes[index]?.getBoundingClientRect().height || 0;
      const pageBudget = result.length === 0 ? Math.max(0, budget - firstPageOffset) : budget;

      if (current.length && currentHeight + height > pageBudget) {
        result.push(current);
        current = [];
        currentHeight = 0;
      }

      current.push(block);
      currentHeight += height;
    });

    if (current.length) result.push(current);
    setPages(result.length ? result : [[]]);
  }, [blocks, budget, firstPageOffset]);

  return { measureRef, pages };
};

export const groupBlocksBySection = (blocks) => {
  const groups = [];
  blocks.forEach((block) => {
    const last = groups[groups.length - 1];
    if (last && last.section === block.section) last.blocks.push(block);
    else groups.push({ section: block.section, blocks: [block] });
  });
  return groups;
};

export function A2PaginationEngine({ blocks, firstPageHeader, children }) {
  const { bodyProbeRef, budget } = useA2PageBudget();
  const headerProbeRef = useRef(null);
  const [firstPageOffset, setFirstPageOffset] = useState(0);

  useEffect(() => {
    const el = headerProbeRef.current;
    if (!el) { setFirstPageOffset(0); return undefined; }

    const measure = () => setFirstPageOffset(el.getBoundingClientRect().height);
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    return () => observer.disconnect();
  }, [firstPageHeader]);

  const { measureRef, pages } = useA2BlockPagination(blocks, budget, firstPageOffset);

  return (
    <>
      <A2Paper probe bodyRef={bodyProbeRef}><div /></A2Paper>
      <div ref={headerProbeRef} className="a2-paper-measure">{firstPageHeader}</div>
      <div ref={measureRef} className="a2-paper-measure">
        {blocks.map((block) => <div key={block.key}>{block.content}</div>)}
      </div>
      {children(pages)}
    </>
  );
}

export default A2Paper;