import { forwardRef } from 'react';

import Logo      from '@/assets/images/al-ansari-color.png';
import Address   from '@/assets/images/al-ansari-full-address.png';
import ContactUs from '@/assets/images/footer.png';

import './A2Paper.css';

const buildGeneratedTimestamp = () => {
  const date = new Date();
  const d = date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const t = date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  return `This document was generated by the system on ${d}, at ${t}.`;
};

const A2Paper = forwardRef(function A2Paper({ children }, ref) {
  return (
    <div ref={ref} className="a2-paper" data-a2-paper-ready="true">
      <div className="a2-paper-header">
        <img className="a2-paper-logo" src={Logo} alt="Company Logo" crossOrigin="anonymous" />
        <img className="a2-paper-address" src={Address} alt="AL Ansari Transport & Enterprises W.L.L" crossOrigin="anonymous" />
      </div>

      <div className="a2-paper-body">
        {children}
      </div>

      <div className="a2-paper-footer">
        <div className="a2-paper-footer-timestamp">{buildGeneratedTimestamp()}</div>
        <img className="a2-paper-footer-contact" src={ContactUs} alt="" crossOrigin="anonymous" />
      </div>
    </div>
  );
});

export default A2Paper;