const MODAL_PALETTES = {
  success: {
    primary: '#114735',
    secondary: '#084632',
    accent: '#34d399',
    textColor: '#ffffff',
    ctaColor: '#065f46',
    icon: 'check',
  },
  error: {
    primary: '#ef4444',
    secondary: '#dc2626',
    accent: '#f87171',
    textColor: '#ffffff',
    ctaColor: '#991b1b',
    icon: 'times',
  },
  warning: {
    primary: '#f59e0b',
    secondary: '#d97706',
    accent: '#fbbf24',
    textColor: '#ffffff',
    ctaColor: '#92400e',
    icon: 'warning',
  },
  updates: {
    primary: '#3b82f6',
    secondary: '#2563eb',
    accent: '#60a5fa',
    textColor: '#ffffff',
    ctaColor: '#1d4ed8',
    icon: 'sync',
  },
  progress: {
    primary: '#8b5cf6',
    secondary: '#7c3aed',
    accent: '#a78bfa',
    textColor: '#ffffff',
    ctaColor: '#6d28d9',
    icon: 'progress',
  },
  announcements: {
    primary: '#06b6d4',
    secondary: '#0891b2',
    accent: '#22d3ee',
    textColor: '#ffffff',
    ctaColor: '#0e7490',
    icon: 'announcement',
  },
  activation: {
    primary: '#6366f1',
    secondary: '#4f46e5',
    accent: '#818cf8',
    textColor: '#ffffff',
    ctaColor: '#3730a3',
    icon: 'key',
  },
  authentication: {
    primary: '#a4c725ff',
    secondary: '#959e17ff',
    accent: '#8daf2fff',
    textColor: '#ffffff',
    ctaColor: '#6e7509ff',
    icon: 'key',
  },
  split: {
    primary: '#a4c725ff',
    secondary: '#959e17ff',
    accent: '#8daf2fff',
    textColor: '#ffffff',
    ctaColor: '#6e7509ff',
    icon: 'sync',
  },
  otp: {
    primary: '#f19763ff',
    secondary: '#c06418ff',
    accent: '#f8d881ff',
    textColor: '#ffffff',
    ctaColor: '#923e17ff',
    icon: 'key',
  },
  form: {
    primary: '#13151a',
    secondary: '#0f0f10',
    accent: '#6e8db5',
    textColor: '#ffffff',
    ctaColor: '#1e40af',
    icon: 'form',
  },
  unauthorized: {
    primary: '#dc2626',
    secondary: '#b91c1c',
    accent: '#f87171',
    textColor: '#ffffff',
    ctaColor: '#991b1b',
    icon: 'lock',
  },
  filters: {
    primary: '#2c2904be',
    secondary: '#96955a7a',
    accent: 'rgb(255, 251, 0)',
    textColor: '#ffffffff',
    ctaColor: 'rgb(117, 124, 11)',
    icon: 'filter',
  },
  fileupload: {
    primary: '#0f172a',
    secondary: '#1e293b',
    accent: '#38bdf8',
    textColor: '#ffffff',
    ctaColor: '#0c4a6e',
    icon: 'form',
  },
  hint: {
    primary: '#0f172a',
    secondary: '#1e293b',
    accent: '#38bdf8',
    textColor: '#ffffff',
    ctaColor: '#0c4a6e',
    icon: 'filter',
  },
};

const DEFAULT_PALETTE = {
  primary: '#b97010',
  secondary: '#969405',
  accent: '#d3b634',
  textColor: '#eeff04',
  ctaColor: '#595f06',
  icon: 'check',
};

export const getModalPalette = (type) => MODAL_PALETTES[type] || DEFAULT_PALETTE;
