import { useNavigate, useParams } from 'react-router-dom';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

import logoImage from '../../assets/images/al-ansari-color.png';
import alAnsariText from '../../assets/images/al-ansari-full-address.png';
import footer from '../../assets/images/footer.png';

import { API_URI } from '../../constants';
import { apiRequest } from '../../utils/api';
import { useHeaderTitle } from '../../Context/HeaderTitleContext';
import { getDeviceFingerprint, getLocationInfo } from '../../utils/deviceFingerprint';
import DevModal from '../../Common/DevModal/DevModal';

import Button from '../../Common/Button/Button';
import './QuotationDoc.css';
import { useState } from 'react';
import { useEffect } from 'react';
import { useRef } from 'react';

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

const SIGN_TYPES = ['accounts', 'pm', 'manager', 'authorized', 'seal'];
const PAGE_BREAK_THRESHOLDS = { PAGE_2: 12, PAGE_3: 48 };

const DEFAULT_COLUMNS = [
  { id: 'description', label: 'Item Description', type: 'text' },
  { id: 'quantity', label: 'Qty', type: 'number' },
  { id: 'unitPrice', label: 'Unit Price(QR)', type: 'number' },
  { id: 'totalPrice', label: 'Total Price(QR)', type: 'calculated' },
];

const DEFAULT_HIRE_ORDER_DATA = {
  vendor: '',
  date: '',
  hireOrderRef: '',
  quoteNo: '',
  attention: '',
  designation: '',
  requestText: '',
  items: [],
  columns: DEFAULT_COLUMNS,
  totalAmount: 0,
  termsAndConditions: [
    'Terms & Conditions',
    'Payment will be made within 90 days from the day of submission of invoice',
  ],
  signatures: {
    accountsDept: 'ACCOUNTS DEPT',
    purchasingManager: 'PURCHASING MANAGER',
    operationsManager: 'OPERATIONS MANAGER',
    authorizedSignatory: 'CEO/MD',
  },
};

const DEFAULT_SIGNATURE_FLAGS = {
  pmSigned: false,
  accountsSigned: false,
  managerSigned: false,
  ceoSigned: false,
};

const DEFAULT_SIGNATURE_STATES = {
  accounts: { url: '', loading: false },
  pm: { url: '', loading: false },
  manager: { url: '', loading: false },
  authorized: { url: '', loading: false },
  seal: { url: '', loading: false },
};

const BG_STYLE_KEYS = ['background', 'backgroundImage', 'backgroundSize', 'backgroundRepeat', 'backgroundPosition', 'backgroundAttachment'];

const SHARED_BTN = {
  variant: 'gradient',
  font: 'md',
  animation: '',
  squircle: '4xl',
  height: '38px',
  width: '160px',
  type: 'submit',
  textColor: 'white-200',
  shadowPosition: 'to-bottom',
  shadowColor: 'white-600',
};

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

const formatCurrency = (value) =>
  (value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const signatoryRole = (name) => name === 'CEO' ? '(CEO)' : '(MANAGING DIRECTOR)';

const buildTimestamp = () => {
  const date = new Date();
  const d = date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const t = date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  return `This document was generated by the system on ${d}, at ${t}.`;
};

const captureElementToCanvas = async (element) => {
  const rootOriginal = {};
  BG_STYLE_KEYS.forEach((key) => { rootOriginal[key] = element.style[key]; });
  Object.assign(element.style, {
    background: '#FFFFFF',
    backgroundImage: 'none',
    backgroundSize: 'auto',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'initial',
    backgroundAttachment: 'initial',
  });

  const children = element.querySelectorAll('*');
  const childOriginals = [];
  children.forEach((child, idx) => {
    childOriginals[idx] = {};
    BG_STYLE_KEYS.forEach((key) => { childOriginals[idx][key] = child.style[key]; });
    if (child.style.backgroundImage && /grid|linear-gradient|repeating/.test(child.style.backgroundImage)) {
      child.style.backgroundImage = 'none';
    }
  });

  const canvas = await html2canvas(element, {
    scale: 2,
    logging: false,
    useCORS: true,
    allowTaint: false,
    scrollX: 0,
    scrollY: 0,
    windowWidth: element.scrollWidth,
    windowHeight: element.scrollHeight,
    backgroundColor: '#FFFFFF',
    ignoreElements: (el) => {
      const cs = window.getComputedStyle(el);
      return cs.backgroundImage && /grid|repeating/.test(cs.backgroundImage);
    },
    removeContainer: true,
    foreignObjectRendering: false,
  });

  Object.assign(element.style, rootOriginal);
  children.forEach((child, idx) => Object.assign(child.style, childOriginals[idx]));

  return canvas;
};

const buildPdf = async () => {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const allDocuments = document.querySelectorAll('.hire-order-document');

  for (let i = 0; i < allDocuments.length; i++) {
    const canvas = await captureElementToCanvas(allDocuments[i]);
    const imgData = canvas.toDataURL('image/png', 1.0);
    const imgWidth = 210;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    if (i > 0) pdf.addPage();
    pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
  }

  return pdf;
};

// ─────────────────────────────────────────────────────────────────────────────
// Sub-components
// ─────────────────────────────────────────────────────────────────────────────

function DocHeader() {
  return (
    <div className="header">
      <div className="logo-placeholder-l">
        <img src={logoImage} alt="Company Logo" />
      </div>
      <div className="company-details-s company-details-l">
        <img src={alAnsariText} alt="AL Ansari Transport & Enterprises W.L.L" />
      </div>
    </div>
  );
}

function SignatureCell({ isSigned, url, alt, className = 'accounts-sign', withSeal = false, sealUrl = '' }) {
  return (
    <td className="sign-table hire-order-signs sign-border-td-r">
      {isSigned && url ? (
        <div className="signature-display">
          <img className={className} src={url} alt={alt} crossOrigin="anonymous" onError={(e) => { e.target.style.display = 'none'; }} />
          {withSeal && sealUrl && (
            <img className="company-seal" src={sealUrl} alt="Company Seal" crossOrigin="anonymous" onError={(e) => { e.target.style.display = 'none'; }} />
          )}
        </div>
      ) : (
        <span className="account-no-signature" />
      )}
    </td>
  );
}

function SignaturesTable({ data, signatureFlags, signatureStates, page1 = true }) {
  const { pmSigned, accountsSigned, managerSigned, ceoSigned } = signatureFlags;
  const { pm, accounts, manager, authorized, seal } = signatureStates;

  return (
    <table className="signatures-table">
      <tbody>
        <tr className="company-name-tr">
          <td colSpan="4" className="company-footer sign-border-td-r">
            AL ANSARI TRANSPORT &amp; ENTERPRISES W.L.L
          </td>
          <td className="sign-table">Subcontractor OR<br />Service Provider</td>
        </tr>

        <tr>
          <td className="sign-table sign-border-td-r sign-border-td-b sign-border-td-t text-align-center">
            Operations Manager
          </td>
          <td className="sign-table sign-border-td-r sign-border-td-b sign-border-td-t text-align-center">
            Purchase Manager
          </td>
          <td className="sign-table sign-border-td-r sign-border-td-b sign-border-td-t text-align-center">
            Accounts Dept:
          </td>
          <td className="sign-table sign-border-td-r sign-border-td-b sign-border-td-t text-align-center">
            Authorized Signatory<br />{signatoryRole(data.signatures.authorizedSignatory)}
          </td>
          <td className="sign-table-date sign-border-td-t">(Date &amp; Sign with Stamp)</td>
        </tr>

        <tr className="hire-order-signature-spaces-large">
          <SignatureCell isSigned={managerSigned} url={manager.url} alt="Manager Signature" />
          <SignatureCell isSigned={pmSigned} url={pm.url} alt="PM Signature" />
          <SignatureCell isSigned={accountsSigned} url={accounts.url} alt="Accounts Signature" />
          <SignatureCell isSigned={ceoSigned} url={authorized.url} alt="Authorized Signature" withSeal sealUrl={seal.url} />
          <td />
        </tr>

        <tr>
          <td className="sign-table sign-border-td-r sign-border-td-t text-align-center">
            {data.signatures.operationsManager}
          </td>
          <td className="sign-table sign-border-td-r sign-border-td-t text-align-center">
            {data.signatures.purchasingManager}
          </td>
          <td className="sign-table sign-border-td-r sign-border-td-t text-align-center">
            {data.signatures.accountsDept}
          </td>
          <td className="sign-table sign-border-td-r sign-border-td-t text-align-center">
            {data.signatures.authorizedSignatory}
          </td>
          <td className="date-no-border" />
        </tr>
      </tbody>
    </table>
  );
}

function ItemsTable({ items, startIndex, showHeader, showTotal, data, calculateTotal, lastItemBorder }) {
  const totalValue = data.totalAmount || calculateTotal();
  const columns = data.columns?.length ? data.columns : DEFAULT_COLUMNS;

  return (
    <table className="hire-order-items-table">
      {showHeader && (
        <thead>
          <tr>
            <th>SN</th>
            {columns.map((col) => <th key={col.id}>{col.label}</th>)}
          </tr>
        </thead>
      )}
      <tbody>
        {items.map((item, idx, arr) => (
          <tr
            key={item._id || item.id || idx}
            className={lastItemBorder && idx === arr.length - 1 ? 'sign-border-td-b' : ''}
          >
            <td>{startIndex + idx}</td>
            {columns.map((col) => (
              <td key={col.id}>
                {(col.id === 'unitPrice' || col.type === 'calculated') ? formatCurrency(item[col.id]) : item[col.id]}
              </td>
            ))}
          </tr>
        ))}
        {showTotal && (
          <tr>
            <td colSpan={columns.length} className="total-label">
              Total Amount (QR)
            </td>
            <td>{formatCurrency(totalValue)}</td>
          </tr>
        )}
      </tbody>
    </table>
  );
}

function TermsTable({ terms, isCompact }) {
  return (
    <table className="terms-table">
      <tbody>
        <tr className={`hire-order-terms-row-large ${isCompact ? 'normal' : 'more'}`}>
          <td className="terms-header-large sign-border-td-r sign-border-td-b sign-border-td-l sign-border-td-t">
            <ul>
              {terms.map((term, idx) => <li key={idx}>{term}</li>)}
            </ul>
          </td>
        </tr>
        <tr>
          <td className="note-row sign-border-td-r sign-border-td-l">
            <strong>NOTE:</strong> The hire order copy should be submitted along with the invoice every month for the payment process.
          </td>
        </tr>
      </tbody>
    </table>
  );
}

function WatermarkDiv({ isSigned, text = '' }) {
  return <div className={isSigned ? 'hire-order-authorized-watermark' : 'hire-order-draft-watermark'}>{text}</div>;
}

function HireOrderDocumentComponent({ data, watermarkText, signatureFlags, signatureStates }) {
  const isFullySigned = signatureFlags.ceoSigned && !!signatureStates.seal.url;
  const itemCount = data.items.length;

  const hasPage2 = itemCount > PAGE_BREAK_THRESHOLDS.PAGE_2;
  const hasPage3 = itemCount > PAGE_BREAK_THRESHOLDS.PAGE_3;

  const page1Items = data.items.slice(0, PAGE_BREAK_THRESHOLDS.PAGE_2);
  const page2Items = data.items.slice(PAGE_BREAK_THRESHOLDS.PAGE_2, PAGE_BREAK_THRESHOLDS.PAGE_3);
  const page3Items = data.items.slice(PAGE_BREAK_THRESHOLDS.PAGE_3);

  return (
    <>
      <div className="hire-order-document" style={{ background: '#FFFFFF', backgroundImage: 'none' }}>
        <WatermarkDiv isSigned={isFullySigned} text={watermarkText} />

        <DocHeader />
        <div className="header-divider" />
        <div className="hire-order-title">HIRE ORDER</div>

        <div className="hire-order-details">
          <table className="details-table">
            <tbody>
              <tr>
                <td className="left-col">
                  <div className="detail-item">TO : {data.vendor}</div>
                  <div className="detail-item">ATTN : {data.attention}</div>
                  <div className="detail-item">DESIGNATION : {data.designation}</div>
                  <div className="detail-item">Ref No : {data.quoteNo}</div>
                </td>
                <td className="right-col">
                  <div className="detail-item">DATE : {data.date}</div>
                  <div className="detail-item">HIRE ORDER REF NO : {data.hireOrderRef}</div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="details-divider" />
        <div className="request-text">{data.requestText}</div>

        <ItemsTable
          items={page1Items}
          startIndex={1}
          showHeader
          showTotal={!hasPage2}
          data={data}
          calculateTotal={() => data.items.reduce((s, i) => s + (i.totalPrice || 0), 0)}
          lastItemBorder={hasPage2}
        />

        {!hasPage2 && (
          <TermsTable terms={data.termsAndConditions} isCompact={itemCount < 8} />
        )}
        {console.log('itemCount:', itemCount, 'hasPage2:', hasPage2, 'hasPage3:', hasPage3)}
        {itemCount <= 12 && (
          <SignaturesTable
            data={data}
            signatureFlags={signatureFlags}
            signatureStates={signatureStates}
            page1
          />
        )}

        <div className="document-timestamp">{buildTimestamp()}</div>
        <div className="footer"><img src={footer} alt="" /></div>
      </div>

      {hasPage2 && (
        <div className="hire-order-document" style={{ background: '#FFFFFF', backgroundImage: 'none' }}>
          <WatermarkDiv isSigned={isFullySigned} text="" />
          <DocHeader />
          <div className="header-divider" />

          <ItemsTable
            items={page2Items}
            startIndex={PAGE_BREAK_THRESHOLDS.PAGE_2 + 1}
            showHeader={hasPage3}
            showTotal={!hasPage3}
            data={data}
            calculateTotal={() => data.items.reduce((s, i) => s + (i.totalPrice || 0), 0)}
            lastItemBorder={hasPage3}
          />

          {!hasPage3 && (
            <TermsTable terms={data.termsAndConditions} isCompact={itemCount < 8} />
          )}

          {itemCount < 42 && (
            <SignaturesTable
              data={data}
              signatureFlags={signatureFlags}
              signatureStates={signatureStates}
              page1={false}
            />
          )}

          <div className="footer"><img src={footer} alt="" /></div>
          <div className="document-timestamp">{buildTimestamp()}</div>
        </div>
      )}

      {hasPage3 && (
        <div className="hire-order-document" style={{ background: '#FFFFFF', backgroundImage: 'none' }}>
          <WatermarkDiv isSigned={isFullySigned} text="" />
          <DocHeader />
          <div className="header-divider" />

          <ItemsTable
            items={page3Items}
            startIndex={PAGE_BREAK_THRESHOLDS.PAGE_3 + 1}
            showHeader
            showTotal
            data={data}
            calculateTotal={() => data.items.reduce((s, i) => s + (i.totalPrice || 0), 0)}
            lastItemBorder={false}
          />

          <TermsTable terms={data.termsAndConditions} isCompact={false} />

          <SignaturesTable
            data={data}
            signatureFlags={signatureFlags}
            signatureStates={signatureStates}
            page1={false}
          />

          <div className="footer"><img src={footer} alt="" /></div>
          <div className="document-timestamp">{buildTimestamp()}</div>
        </div>
      )}
    </>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Main Component
// ─────────────────────────────────────────────────────────────────────────────

function QuotationDoc() {
  const navigate = useNavigate();
  const componentRef = useRef();
  const { refNo } = useParams();
  const { setHeaderTitle, setHeaderSubtitle } = useHeaderTitle();

  const [hireOrderData, setHireOrderData] = useState(DEFAULT_HIRE_ORDER_DATA);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [imagesLoaded, setImagesLoaded] = useState(false);

  const [signatureFlags, setSignatureFlags] = useState(DEFAULT_SIGNATURE_FLAGS);
  const [signatureStates, setSignatureStates] = useState(DEFAULT_SIGNATURE_STATES);

  const [hireOrderAuthSignatoryTitle, setHireOrderAuthSignatoryTitle] = useState('CEO');
  const [isSigningDoc, setIsSigningDoc] = useState(false);
  const [showSignConfirmModal, setShowSignConfirmModal] = useState(false);
  const [showUnauthorisedModal, setShowUnauthorisedModal] = useState(false);
  const [signResult, setSignResult] = useState(null);
  const [vendorMail, setVendorMail] = useState(null);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailFormValues, setEmailFormValues] = useState({ emails: [''] });
  const [isSendingEmail, setIsSendingEmail] = useState(false);
  const [showOverrideModal, setShowOverrideModal] = useState(false);
  const [unsignedAboveRoles, setUnsignedAboveRoles] = useState([]);
  const [deviceInfo, setDeviceInfo] = useState(null);
  const [activationKey, setActivationKey] = useState('');
  const [activationError, setActivationError] = useState('');
  const [activationLoading, setActivationLoading] = useState(false);
  const [globalActivation, setGlobalActivation] = useState({ isActivated: false, isTrusted: false, checked: false });
  const [showActivationModal, setShowActivationModal] = useState(false);
  const [showTrustModal, setShowTrustModal] = useState(false);
  const [showNotTrustedModal, setShowNotTrustedModal] = useState(false);
  const [showUploadSuccessModal, setShowUploadSuccessModal] = useState(false); 

  useEffect(() => {
    setHeaderTitle('Quotation Document');
    setHeaderSubtitle(refNo || 'Quotation');
    return () => { setHeaderTitle(null); setHeaderSubtitle(null); };
  }, [refNo, setHeaderTitle, setHeaderSubtitle]);

  useEffect(() => {
    const initializeDeviceInfo = async () => {
      try {
        const fingerprint = getDeviceFingerprint();
        const location = await getLocationInfo();
        const user = JSON.parse(localStorage.getItem('user') || '{}');

        if (!user._id) {
          console.warn('[QuotationDoc] User ID not found in localStorage');
          setGlobalActivation({ isActivated: false, isTrusted: false, checked: true });
          return;
        }

        const info = {
          userId: user._id,
          deviceFingerprint: fingerprint.uniqueCode,
          ipAddress: location.ipAddress,
          location: `${location.city}, ${location.region}, ${location.country}`,
          userAgent: fingerprint.userAgent,
          browserInfo: fingerprint.browserInfo,
        };

        setDeviceInfo(info);

        const status = await checkAllSignTypeTrust(info);
        setGlobalActivation({ ...status, checked: true });

      } catch (err) {
        console.error('[QuotationDoc] Failed to initialize device info:', err);
        setGlobalActivation({ isActivated: false, isTrusted: false, checked: true });
      }
    };

    initializeDeviceInfo();
  }, []);

  useEffect(() => {
    if (globalActivation.isActivated && globalActivation.isTrusted && deviceInfo && !loading) {
     loadAllSignatures(deviceInfo, signatureFlags);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [globalActivation.isTrusted, globalActivation.isActivated, deviceInfo, loading]);

  useEffect(() => {
    if (!componentRef.current) { setImagesLoaded(true); return; }

    const checkImages = () => {
      const images = componentRef.current.querySelectorAll('img');
      if (!images.length) { setImagesLoaded(true); return; }

      let loadedCount = 0;
      const onLoad = () => { if (++loadedCount === images.length) setImagesLoaded(true); };

      images.forEach((img) => {
        if (img.complete && img.naturalHeight !== 0) { onLoad(); }
        else { img.addEventListener('load', onLoad); img.addEventListener('error', onLoad); }
      });
    };

    const timer = setTimeout(checkImages, 500);
    return () => clearTimeout(timer);
  }, [hireOrderData, signatureStates]);

  // ── Signature loading ──────────────────────────────────────────────────────

  /**
   * Loads a signature image for a given sign type.
   * For 'authorized', uses authTitle to determine if it's CEO or MD signature.
   * @param {string} signType  - One of: pm, accounts, manager, authorized, seal
   * @param {Object} info     - Device info.
   * @param {Object} flags    - Signature flags to check.
   * @param {string} [authTitle] - Authorized signatory title (CEO or MANAGING DIRECTOR).
   */
  const loadSignature = async (signType, info, flags, authTitle = hireOrderAuthSignatoryTitle) => {
    const flagMap = {
      accounts: flags.accountsSigned,
      pm: flags.pmSigned,
      manager: flags.managerSigned,
      authorized: flags.ceoSigned,
      seal: flags.ceoSigned,
    };

    if (!flagMap[signType]) return;

    setSignatureStates((prev) => ({ ...prev, [signType]: { ...prev[signType], loading: true } }));

    try {
      const payload = { deviceInfo: info };
      // For authorized signatory, pass the role (CEO or MD) so backend returns correct signature key
      if (signType === 'authorized' && authTitle === 'MANAGING DIRECTOR') {
        payload.authRole = 'MANAGING_DIRECTOR';
      }
      
      const keyResponse = await apiRequest(`${API_URI}/users/doc-oauth-${signType}-sign-key`, 'POST', payload);
      if (!keyResponse.ok) throw new Error('Failed to get signature key');
      const keyData = await keyResponse.json();

      const s3Response = await apiRequest(`${API_URI}/s3/get-pre-signed-url`, 'POST', { key: keyData.data.sign_key, isLong: false, isLpoSign: true });
      if (!s3Response.ok) throw new Error('Failed to get signature URL');
      const s3Data = await s3Response.json();

      setSignatureStates((prev) => ({ ...prev, [signType]: { url: s3Data.dataUrl, loading: false } }));

    } catch (err) {
      console.error(`[LpoDoc] loadSignature(${signType}) error:`, err);
      setSignatureStates((prev) => ({ ...prev, [signType]: { url: '', loading: false } }));
    }
  };

  /** Loads all five signature slots in parallel. */
  const loadAllSignatures = (info, flags, authTitle = hireOrderAuthSignatoryTitle) =>
    Promise.all(SIGN_TYPES.map((t) => loadSignature(t, info, flags, authTitle)));

  // ── Signature button handler ──────────────────────────────────────────

  /** Handle signature button opens the appropriate modal. */
  const handleSignButtonClick = async () => {
    if (!deviceInfo) {
      alert('Device info not ready. Please wait and try again.');
      return;
    }

    try {
      const response = await apiRequest(`${API_URI}/users/verify-device-trust`, 'POST', {
        signType: 'pm',
        deviceInfo,
      });
      const result = await response.json();

      // ── Guard against missing data shape ──
      const isActivated = result?.data?.isActivated ?? result?.isActivated ?? false;
      const isTrusted = result?.data?.isTrusted ?? result?.isTrusted ?? false;

      if (!isActivated) { setShowActivationModal(true); return; }
      if (!isTrusted) { setShowNotTrustedModal(true); return; }

      setShowSignConfirmModal(true);
    } catch (err) {
      console.error('[LpoDoc] handleSignButtonClick error:', err);
      alert(`Could not verify device trust: ${err.message}`);
    }
  };

  // ── Signature confirmation ──────────────────────────────────────────

  /** Handle signature confirmation and signing. */
  const handleConfirmSign = async (override = false) => {
     if (!deviceInfo) return;
     const user = JSON.parse(localStorage.getItem('user') || '{}');
     if (!user._id) { alert('User session not found. Please log in again.'); return; }

     setIsSigningDoc(true);
     setShowSignConfirmModal(false);
     setShowOverrideModal(false);

     try {
       const response = await apiRequest(
         `${API_URI}/hire-order/sign/${encodeURIComponent(decodeURIComponent(refNo))}`,
         'POST',
         {
           uniqueCode:     user.uniqueCode,
           signedDate:     new Date().toISOString(),
           signedFrom:     deviceInfo.browserInfo,
           signedIP:       deviceInfo.ipAddress,
           signedDevice:   deviceInfo.userAgent,
           signedLocation: deviceInfo.location,
           override,                               
         }
       );

       const result = await response.json();

       if (response.status === 403) {
         result.message === 'LPO_NOT_UPLOADED' ? setSignResult('not_uploaded') : setShowUnauthorisedModal(true);
         return;
       }
       if (response.status === 409) { setSignResult('already_signed'); return; }

       // ── Out-of-order: backend returned 202 requireOverride ──────────────────
       if (response.status === 202 && result.requireOverride) {
         const roleLabels = {
           PURCHASE_MANAGER:  'Purchase Manager',
           MANAGER:           'Operations Manager',
           CEO:               'CEO',
           MANAGING_DIRECTOR: 'Managing Director',
           ACCOUNTS:          'Accounts Dept',
         };
         const labels = (result.unsignedAbove || []).map(r => roleLabels[r] || r);
         setUnsignedAboveRoles(labels);
         setShowOverrideModal(true);
         return;
       }

       if (!response.ok) throw new Error(result.message || 'Signing failed');

       // ── Success ──────────────────────────────────────────────────────────────
       const lpo      = result.data;
       const newFlags = {
         pmSigned:       lpo.pmSigned       || false,
         accountsSigned: lpo.accountsSigned || false,
         managerSigned:  lpo.managerSigned  || false,
         ceoSigned:      lpo.ceoSigned      || false,
       };
       setSignatureFlags(newFlags);
       setSignResult('success');
       await loadAllSignatures(deviceInfo, newFlags);

     } catch (err) {
       console.error('[LpoDoc] handleConfirmSign error:', err);
       alert(`Signing failed: ${err.message}`);
     } finally {
       setIsSigningDoc(false);
     }
   };

  // ── Email handler ──────────────────────────────────────────────────────────

  /** Generates PDF and sends Quotation to vendor via email. */
  const handleSendEmail = async (extraFiles = []) => {
    const validEmails = emailFormValues.emails.filter(e => e?.includes('@'));
    if (!validEmails.length) { alert('Please enter at least one valid email'); return; }

    setIsSendingEmail(true);
    const controls = document.querySelector('.hire-order-controls');
    if (controls) controls.style.visibility = 'hidden';

    try {
      await new Promise((r) => setTimeout(r, 200));
      const pdf = await buildPdf();
      const pdfBlob = pdf.output('blob');
      const extractName = (str) => str ? str.split('-')[0].trim() : '';

      const formDataToSend = new FormData();
      formDataToSend.append('pdf', pdfBlob, `${getFileName()}.pdf`);
      formDataToSend.append('emails', JSON.stringify(validEmails));
      formDataToSend.append('recipientName', extractName(hireOrderData.attention));
      formDataToSend.append('vendorName', extractName(hireOrderData.vendor));
      formDataToSend.append('hireOrderRef', decodeURIComponent(refNo));

      // append any extra attachments
      extraFiles.forEach((file) => formDataToSend.append('attachments', file));

      const response = await apiRequest(`${API_URI}/hire-order/send-via-email`, 'POST', formDataToSend, true);

      if (response.ok) {
        setShowEmailModal(false);
        setEmailFormValues({ emails: [''] });
        setSignResult('email_sent');
      } else {
        alert('Failed to send email. Please try again.');
      }
    } catch (err) {
      console.error('[LpoDoc] handleSendEmail error:', err);
      alert('Error sending email.');
    } finally {
      if (controls) controls.style.visibility = 'visible';
      setIsSendingEmail(false);
    }
  };

  // ── Signature activation handlers ──────────────────────────────────────────

  /** Checks activation status and opens the appropriate modal. */
  const handleLoadAllSignatures = async () => {
    const status = await checkAllSignTypeTrust(deviceInfo);

    if (!status.isActivated) { setShowActivationModal(true); return; }
    if (!status.isTrusted)   { setShowNotTrustedModal(true); return; }

    await loadAllSignatures();
  };

  /** Submits the 20-digit activation key for all sign types. */
  const handleActivation = async () => {
    if (activationKey.length !== 20) {
      setActivationError('Please enter a valid 20-digit activation key');
      return;
    }

    setActivationLoading(true);
    setActivationError('');

    try {
      for (const signType of SIGN_TYPES) {
        const response = await apiRequest(
          `${API_URI}/users/activate-signature`,
          'POST',
          { activationKey, signType, deviceInfo }
        );
        if (!response.ok) {
          const errData = await response.json();
          throw new Error(errData.message || `Failed to activate ${signType}`);
        }
      }

      setShowActivationModal(false);
      setActivationKey('');
      setActivationError('');
      setShowTrustModal(true);

    } catch (err) {
      console.error('[LpoDoc] Activation error:', err);
      setActivationError(`${err.message}, failed attempt, refresh and try again`);
    } finally {
      setActivationLoading(false);
    }
  };

  /** Confirms browser trust after successful activation, then loads all signatures. */
  const confirmBrowserTrust = () => {
    setShowTrustModal(false);
    setGlobalActivation({ isActivated: true, isTrusted: true, checked: true });
    loadAllSignatures(deviceInfo, signatureFlags);
  };

  // ── Signature trust check ──────────────────────────────────────────────────

  /**
   * Checks device trust for all sign types via the API.
   * Returns an aggregate { isActivated, isTrusted } result.
   *
   * @param {Object} info - Device info object.
   * @returns {Promise<{ isActivated: boolean, isTrusted: boolean }>}
   */
  const checkAllSignTypeTrust = async (info) => {
    if (!info) return { isActivated: false, isTrusted: false };

    try {
      let allActivated = true;
      let allTrusted   = true;

      for (const signType of SIGN_TYPES) {
        const response = await apiRequest(`${API_URI}/users/verify-device-trust`, 'POST', { signType, deviceInfo: info });
        const result   = await response.json();
        if (!result.data.isActivated) allActivated = false;
        if (!result.data.isTrusted)   allTrusted   = false;
      }

      return { isActivated: allActivated, isTrusted: allTrusted };
    } catch (err) {
      console.error('[LpoDoc] checkAllSignTypeTrust error:', err);
      return { isActivated: false, isTrusted: false };
    }
  };

  const fetchHireOrder = async () => {
    setLoading(true);
    setError(null);
    setImagesLoaded(false);

    try {
      if (!refNo) throw new Error('No hire order reference number provided');

      const decodedRef = decodeURIComponent(refNo);
      const response = await apiRequest(`${API_URI}/hire-order/get-hire-order-by-ref/${decodedRef}`, 'GET');

      if (!response.ok) {
        throw new Error(`HTTP error ${response.status}`);
      }

      const data = await response.json();
      if (!data.success || !data.data) {
        setError(data.message || 'Hire order not found');
        return;
      }

      const order = data.data;
      const flags = {
        pmSigned: order.pmSigned || false,
        accountsSigned: order.accountsSigned || false,
        managerSigned: order.managerSigned || false,
        ceoSigned: order.ceoSigned || false,
      };

      const builtData = {
        vendor: order.company?.vendor || '',
        date: order.date || '',
        hireOrderRef: order.hireOrderRef || '',
        quoteNo: order.quoteNo || '',
        attention: order.company?.attention || '',
        designation: order.company?.designation || '',
        requestText: order.requestText || '',
        items: order.items || [],
        columns: order.columns?.length ? order.columns : DEFAULT_COLUMNS,
        totalAmount: order.totalAmount || 0,
        termsAndConditions: order.termsAndConditions || DEFAULT_HIRE_ORDER_DATA.termsAndConditions,
        signatures: order.signatures || DEFAULT_HIRE_ORDER_DATA.signatures,
      };

      setHireOrderData(builtData);
      setSignatureFlags(flags);
      setHireOrderAuthSignatoryTitle(order.signatures?.authorizedSignatoryTitle || 'CEO');
      setVendorMail(order.vendorMail || null);

      if (globalActivation.isActivated && globalActivation.isTrusted && deviceInfo) {
        await loadAllSignatures(deviceInfo, flags, order.signatures?.authorizedSignatoryTitle || 'CEO');
      }

    } catch (err) {
      console.error('[QuotationDoc] fetchHireOrder error:', err);
      setError(`Failed to load hire order: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (refNo && globalActivation.checked && deviceInfo) fetchHireOrder();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refNo, globalActivation.checked, deviceInfo]);

  /** Generates the PDF, uploads it to S3 via the API, and notifies the user. */
  const sendToApprove = async () => {
    if (!guardImagesLoaded()) return;

    await withControlsHidden(async () => {
      try {
        const pdf     = await buildPdf();
        const pdfBlob = pdf.output('blob');

        const uploadResponse = await apiRequest(
          `${API_URI}/hire-order/upload-hire-order`,
          'POST',
          {
            fileName:    `${getFileName()}.pdf`,
            uploadedBy:  'WORKSHOP_MANAGER',
            hireOrderRef: decodeURIComponent(refNo),
            description: 'Hire order document generated from system',
          },
          { 'Content-Type': 'application/json' }
        );

        const uploadResult = await uploadResponse.json();
        if (!uploadResponse.ok || !uploadResult.success) {
          throw new Error(uploadResult.message || 'Upload failed');
        }

        const s3Response = await fetch(uploadResult.data?.uploadUrl || uploadResult.uploadUrl, {
          method:  'PUT',
          headers: { 'Content-Type': 'application/pdf' },
          body:    pdfBlob,
        });

        if (!s3Response.ok) throw new Error(`S3 upload failed: ${s3Response.status} ${s3Response.statusText}`);

        setShowUploadSuccessModal(true);

      } catch (err) {
        console.error('[LpoDoc] sendToApprove error:', err);
        alert(`Upload failed: ${err.message}`);
      }
    });
  };

  const guardImagesLoaded = () => {
    if (!imagesLoaded) { alert('Please wait for all images to load before generating PDF'); return false; }
    return true;
  };

  const withControlsHidden = async (action) => {
    const controls = document.querySelector('.hire-order-controls');
    if (controls) controls.style.visibility = 'hidden';
    try {
      await action();
    } finally {
      if (controls) controls.style.visibility = 'visible';
    }
  };

  const handleDownloadPdf = async () => {
    if (!guardImagesLoaded()) return;
    await withControlsHidden(async () => {
      try {
        const pdf = await buildPdf();
        pdf.save(`${getFileName()}.pdf`);
      } catch (err) {
        console.error('[QuotationDoc] handleDownloadPdf error:', err);
        alert('Error generating PDF. Please try again.');
      }
    });
  };

  const getFileName = () => `HO-${hireOrderData.hireOrderRef}-${hireOrderData.vendor}`;

  if (loading) {
    return (
      <div className="hire-order-page-container">
        <div className="loading-container">
          <p>Loading Quotation data...</p>
          <p>Reference: {refNo ? decodeURIComponent(refNo) : 'No reference provided'}</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="hire-order-page-container">
        <div className="error-container">
          <p className="error-message">{error}</p>
          <p>Reference: {refNo ? decodeURIComponent(refNo) : 'No reference provided'}</p>
          <button onClick={fetchHireOrder} className="retry-button">Retry</button>
        </div>
      </div>
    );
  }

  const allSigned = hireOrderData && signatureFlags.managerSigned && signatureFlags.pmSigned && signatureFlags.accountsSigned && signatureFlags.ceoSigned;

  return (
    <div className="hire-order-page-container" ref={componentRef}>

    <div className="hire-order-controls">
      <div className="activation-buttons-section">
        {!globalActivation.checked ? (
          <div className="status-badge checking">🔄 Checking Status...</div>
        ) : !globalActivation.isActivated ? (
          <Button {...SHARED_BTN} text="Activate E-Signs" onClick={handleLoadAllSignatures} colorScheme="red-700" />
        ) : !globalActivation.isTrusted ? (
    <div className="status-badge not-trusted">
            <Button {...SHARED_BTN} text="Device Not Trusted - Contact Admin" onClick={handleLoadAllSignatures} colorScheme="red-700" />
          </div>
        ) : null}
      </div>

      <div className="button-group">
        <div className="managerial-actions">
          <Button {...SHARED_BTN} text="Send For Approval" onClick={sendToApprove} colorScheme="lime-700" />
          <Button {...SHARED_BTN} text={isSigningDoc ? 'Signing...' : 'Sign Document'} onClick={handleSignButtonClick} colorScheme="indigo-700" disabled={isSigningDoc} />
          <Button {...SHARED_BTN} text="Download as PDF" onClick={handleDownloadPdf} colorScheme="violet-800" />
        </div>
        <div className="managerial-actions">
      <Button {...SHARED_BTN} text="Send to Supplier" onClick={() => { if (vendorMail?.length) setEmailFormValues({ emails: vendorMail }); setShowEmailModal(true); }} colorScheme="rose-700" />
          <Button {...SHARED_BTN} text="Edit" onClick={() => navigate(`/hire-order-form/${encodeURIComponent(decodeURIComponent(refNo))}`)} colorScheme="sky-800" />
        </div>
      </div>
    </div>

    <HireOrderDocumentComponent
       data={hireOrderData}
       watermarkText=""
       signatureFlags={signatureFlags}
       signatureStates={signatureStates}
    />

    <DevModal
      isOpen={showActivationModal}
      onClose={() => setShowActivationModal(false)}
      type="activation"
      title="Activate Signatures"
      message="Enter your 20-digit activation key to activate all signatures"
      showInput
      useCellInput
      cellCount={20}
      inputValue={activationKey}
      onInputChange={setActivationKey}
      inputError={activationError}
      deviceInfo={deviceInfo}
      buttonText={activationLoading ? 'Activating...' : 'Activate'}
      onButtonClick={handleActivation}
      preventClose={activationLoading}
    />

    <DevModal
      isOpen={showTrustModal}
      onClose={() => {}}
      type="success"
      title="Key has been Activated"
      message="Your key has been activated now. You can able to load and use all signatures."
      buttonText="Trust this browser"
      onButtonClick={confirmBrowserTrust}
      preventClose
    />

    <DevModal
      isOpen={showNotTrustedModal}
      onClose={() => setShowNotTrustedModal(false)}
      type="warning"
      title="Device Not Trusted"
      message="This device is activated but not yet trusted by the administrator. Please contact your system administrator to enable trust for this device."
      buttonText="Close"
      onButtonClick={() => setShowNotTrustedModal(false)}
    />

    <DevModal
      isOpen={showSignConfirmModal}
      onClose={() => setShowSignConfirmModal(false)}
      type="warning"
      title="Confirm Signature"
      message="You are about to sign this Quotation document. This action cannot be undone."
      buttonText="Confirm & Sign"
      onButtonClick={handleConfirmSign}
      secondaryButtonText="Cancel"
      onSecondaryClick={() => setShowSignConfirmModal(false)}
    />

    <DevModal
      isOpen={showUnauthorisedModal}
      onClose={() => setShowUnauthorisedModal(false)}
      type="unauthorized"
      title="Not Authorised"
      message="Your account is not registered as an authorised signatory for hire order documents."
      unauthorizedReason="Your user ID does not match any of the four authorised signatories."
      buttonText="Close"
      onButtonClick={() => setShowUnauthorisedModal(false)}
    />

   <DevModal
      isOpen={signResult === 'not_uploaded'}
      onClose={() => setSignResult(null)}
      type="warning"
      title="Quotation Not Ready for Signing"
      message="This hire order has been created but not yet uploaded for approval. Please ask the creator to upload the document first before signing."
      buttonText="OK"
      onButtonClick={() => setSignResult(null)}
    />

    <DevModal
      isOpen={signResult === 'already_signed'}
      onClose={() => setSignResult(null)}
      type="warning"
      title="Already Signed"
      message="This signature position has already been signed on this document."
      buttonText="OK"
      onButtonClick={() => setSignResult(null)}
    />

    <DevModal
      isOpen={showOverrideModal}
      onClose={() => setShowOverrideModal(false)}
      type="warning"
      title="Signatures Pending"
      message={`The following ${unsignedAboveRoles.length > 1 ? 'people have' : 'person has'} not yet signed this document:\n\n${unsignedAboveRoles.join(', ')}\n\nYou can wait for them to sign first, or override and sign now. If you override, they will be notified to sign.`}
      buttonText="Override & Sign"
      onButtonClick={() => handleConfirmSign(true)}
      secondaryButtonText="Wait"
      onSecondaryClick={() => setShowOverrideModal(false)}
    />

    <DevModal
      isOpen={signResult === 'success'}
      type="success"
      title="Document Signed"
      message="Your signature has been recorded successfully."
      buttonText="OK"
      onButtonClick={() => setSignResult(null)}
      autoClose
      autoCloseDelay={3000}
    />

    <DevModal
      isOpen={showEmailModal}
      onClose={() => { setShowEmailModal(false); setEmailFormValues({ emails: [''] }); }}
      type="form"
      title="Send to Supplier"
      message="Enter recipient email addresses. Add more than one if needed."
      buttonText={isSendingEmail ? 'Sending...' : 'Send'}
      onButtonClick={() => {
        const validEmails = emailFormValues.emails.filter(e => e?.includes('@'));
        if (!validEmails.length) { alert('Please enter at least one valid email'); return; }
        handleSendEmail([]);
      }}
      secondaryButtonText="Cancel"
      onSecondaryClick={() => { setShowEmailModal(false); setEmailFormValues({ emails: [''] }); }}
     formFields={[{ name: 'emails', label: 'Recipient Emails (comma-separated)', type: 'text', placeholder: 'vendor@example.com, other@example.com', required: true }]}
      formValues={{ emails: emailFormValues.emails.join(', ') }}
      onFormChange={(field, value) => setEmailFormValues({ emails: value.split(',').map(e => e.trim()).filter(Boolean) })}
    />

    <DevModal
      isOpen={showUploadSuccessModal}
      onClose={() => setShowUploadSuccessModal(false)}
      type="success"
      title="Quotation Uploaded"
      message="The hire order document has been uploaded successfully for approval."
      buttonText="OK"
      onButtonClick={() => setShowUploadSuccessModal(false)}
      autoClose
      autoCloseDelay={3000}
    />

    <DevModal
      isOpen={signResult === 'email_sent'}
      onClose={() => setSignResult(null)}
      type="success"
      title="Quotation Sent Successfully"
      message="Hire order sent successfully to supplier."
      buttonText="OK"
      onButtonClick={() => setSignResult(null)}
      autoClose
      autoCloseDelay={3000}
    />
    </div>
  );
}

export default QuotationDoc;
